version: '3'
services:
  db-service:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=Timeflippers.123
      - MYSQL_DATABASE=timeflip
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    ports:
      - 3307:3306

  app:
    build: .
    image: app:latest
    ports:
      - 8080:8080
    depends_on:
      - db-service