version: '3'
services:
  app:
    container_name: app-container
    restart: always
    build: .
    volumes:
      - ~/.m2:/home/nonroot/.m2
    expose:
      - "8080"

    ports:
      - 8080:8080

    networks:
      - webapp-mysql-network
    depends_on:
      - db
  db:
    container_name: db-container
    image: mysql:5.7
    networks:
      - webapp-mysql-network
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=Timeflippers.123
      - MYSQL_DATABASE=db-timeflip
networks:
  webapp-mysql-network:
    driver: bridge